In [1]:
#1 Create a 1D array
import numpy as np 

Darray= np.arange(10)
print(Darray)

    





[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2 Create 3x3 NumPy array of All Boolena values Trues 

bool_true = np.ones((3,3), dtype=bool)
print('3x3 Numpy Array with Trues : ')
print(bool_true)

3x3 Numpy Array with Trues : 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [2]:
#3 Extract all odd numbers from array of 1-10 ) 
array = np.arange(10)
array[array % 2 == 1]

array([1, 3, 5, 7, 9])

In [12]:
#4 Replace all odd numbers from array of (1-10)
array = np.arange(1,10)
array[array % 2 == 1] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#5 Convert a 1D array to 2D array with 2 rows 
array = np.arange(3, 15).reshape(2, 6)
print(array)

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]]


In [3]:
#6 Create two arrays a and b , stack them two arrays vertically 
# use the np.dot and np.sum to calculate totals 
x = np.arange(3, 12).reshape(3, 3)
y = np.arange(5, 14).reshape(3, 3) 
z=np.vstack((x,y))
array = np.dot(x, y)
sum=np.sum(array)

print(z)


print(array)
print (sum)




[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[102 114 126]
 [174 195 216]
 [246 276 306]]
1755


#extension

In [35]:
#Extension 1 Create array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])
x = np.array([1,2,3])
np.r_[np.repeat(x, 3), np.tile(x, 3)]



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
#Extension2 in two arrays a(1,2,3,4,5) and b(4,5,6,7,8,9) - remove all repeating items present in array b
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c = np.setdiff1d(b, a)
print(c)


[6 7 8 9]


In [13]:
#Get all items between 3 and 7 from a and b and sum themtogether
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c= np.concatenate((a, b))
print(c)

c[(c > 3) & (c < 7)].sum()



[1 2 3 4 5 4 5 6 7 8 9]


24